#!/bin/sh
# start stop hotspot

start() {
        echo "Starting glxgears"
        export DISPLAY=:0
        glxgears &
}

stop() {
        echo "Killing glxgears"
        killall glxgears
        echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1

esac
exit $?
