#!/bin/sh
# start stop hotspot

start() {
        echo "Starting quake"
        export DISPLAY=:0
        /root/ioquake3.arc &
}

stop() {
        echo "Killing glxgears"
        killall ioquake3.arc
        if [ $? -eq 0 ]
        then
                echo "OK"
        else
                echo "Error: Unable to stop quake" >&2
        fi

}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1

esac
exit $?
