#!/bin/sh
# connect to wifi access point

start() {
        # wpa_supplicant up
        echo "Connecting: "
	wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
	udhcpc -i wlan0
        echo "OK"
}
stop() {
        echo "Stopping hostapd"
        killall wpa_supplicant
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1

esac
exit $?

